### ISSUE TITLE
webpack打包编译IE下访问不兼容报错

### ISSUE THREAD

**Issue by huang-x-h** [Justineo/resize-detector#16]
包在发布定义了 `module` 走的是  `esm` 方式，通过 `webpack` 打包后，在 `ie` 下运行报错，应该要走 `main` 字段对应文件

建议在定义一个 `browser`  字段去指定到 `dist/index.js`

**Comment by Justineo** [comment]
https://github.com/Justineo/resize-detector#heads-up

这是预期行为，目前提供的 ESM 版本不转译，请指定 Babel Loader 处理此模块。
