### ISSUE TITLE
Can not  trigger resize-listener by javascript dispatchEvent?

### ISSUE THREAD

**Issue by zl7261** [Justineo/resize-detector#17]
Vue-charts use resize-detector to auto-resize the chart.

I want to dispatch a resize event by manual when the user clicks the menu-fold button so can trigger the Chart resize and reRender.

But how to trigger the detector by javascript?

Here is my code,didn't trigger the detector.

```javascript
let resizeEvent = new Event('resize')

document.dispatchEvent(resizeEvent)

document.onresize = function(){console.log(1)}
```

**Comment by Justineo** [comment]
Why would you dispatch a `resize` event manually? `resize-detector` should trigger the callback when the target element is resized.

**Comment by zl7261** [comment]
> Why would you dispatch a `resize` event manually? `resize-detector` should trigger the callback automatically whenever the target element is resized.

You mean I should dispatch the resize event on the Element which I add resize-listener, not on the document?

**Comment by Justineo** [comment]
You don't need to dispatch anything. The component should resize whenever the size of its root element changes.

Be sure to set a `autoresize` prop on it.
