### ISSUE TITLE
安卓钉钉报错`unexpected strict mode reserved word`

### ISSUE THREAD

**Issue by losymear** [Justineo/resize-detector#2]
描述:在vue项目引用`vue-echart`包后，安卓钉钉的内置浏览器会报`unexpected strict mode reserved word`错误无法显示页面。但在IOS钉钉内置浏览器能正常显示页面。
![screenshot_2018-04-28-18-12-06-126_com alibaba android rimet_ b f007e99](https://user-images.githubusercontent.com/30641746/39395341-22648c16-4b10-11e8-9cb3-b56160f4f0cf.png)
![screenshot_2018-04-28-18-14-46-283_com alibaba android rimet_ b ec0b6b4](https://user-images.githubusercontent.com/30641746/39395343-254214e4-4b10-11e8-997e-af42c4aad762.png)

经过一段时间排查发现将`resize-detector`包的` "module": "esm/index.js"`删除后能够正常显示。
估计`esm/index.js`的源码里有变量被安卓版钉钉浏览器当做保留字.

**Comment by Justineo** [comment]
请严格按 vue-echarts 的 README 配置 babel-loader。
