### ISSUE TITLE
对源码的两处疑问

### ISSUE THREAD

**Issue by STLighter** [Justineo/resize-detector#3]
阅读源码后有感觉有几处细节有问题, 但限于测试环境有限, 没办法验证, 因此在这里列一下:
1.  `__resize_mutation_handler__` 在`removeListener`中是否需要置为`null`? (不知道ie9/10中内存回收机制如何, 会不会产生内存泄漏问题, 在chrome下不置为`null`是没有问题的. 

2. `removeListener`中对IE9/10的处理是否需要移到`if (!listeners.length) {}`中?
https://github.com/Justineo/resize-detector/blob/1498d78dd664b4b41ff44cda529a76184e4e052a/src/index.js#L73

另外demo中有一些小问题:
1. 莫名出现的`</button>`
https://github.com/Justineo/resize-detector/blob/master/demo/index.html#L91

2. IE不支持字符串模板语法
https://github.com/Justineo/resize-detector/blob/master/demo/index.html#L115

**Comment by Justineo** [comment]
> __resize_mutation_handler__ 在removeListener中是否需要置为null

理论上应该最好是清掉的。



> removeListener中对IE9/10的处理是否需要移到if (!listeners.length) {}中?

这个不判断不影响吧，early return 我觉得也 OK。



> 莫名出现的</button>

Typo.

> IE不支持字符串模板语法

Log 后来加的，我找时间改一下。

**Comment by STLighter** [comment]
@Justineo 我理解resize-detector支持对同一个dom元素绑定多个callback, 而且callback都是放在`__resize_listeners__`中的. 所以在`remove`时都应该先走从`__resize_listeners__`中移除callback的操作, 直接early return可能会导致其他callback无法执行, 同时`__resize_listeners__`数组没有清除.

目前我这里环境有限, 走不到IE9/10这个条件分支, 所以没法实际测试出有没有这些问题, 还是说IE下有一些我不知道的feature会避免这些问题的发生?

**Comment by Justineo** [comment]
现在不方便看，我有时间的时候再仔细看一下吧。

**Comment by STLighter** [comment]
10棒
