### ISSUE TITLE
安装报错请尽快修复

### ISSUE THREAD

**Issue by jiahui336** [Justineo/resize-detector#30]
Invalid response body while trying to fetch https://registry.npmjs.org/resize-detector: Cannot read properties of null (reading 'pickAlgorithm')

**Comment by Justineo** [comment]
It's clearly not related to this project.

**Comment by jiahui336** [comment]
> It's clearly not related to this project.

vue-echarts 不是也用到这个插件了吗，不是这个的问题吗，是我node版本的问题？

**Comment by Justineo** [comment]
The error message shows that there is issue downloading the package from npm, which cannot be caused by the package itself.
