### ISSUE TITLE
getComputedStyle(...) is null on Firefox

### ISSUE THREAD

**Issue by phoenixwong** [Justineo/resize-detector#4]
![getcomputedstyle-is-null-on-ff](https://user-images.githubusercontent.com/6954306/44643614-c023de00-aa03-11e8-92a6-3a83ce5cc24e.png)

**Browser:** Firefox 61.0.0
**OS:** Windows 10,  Mac OS X 10.13

Looks similar to this Stackoverflow issue: https://stackoverflow.com/questions/46127213/how-to-fix-typeerror-window-getcomputedstyle-is-null-in-firefox

**Comment by Justineo** [comment]
Thanks for reporting!
