### ISSUE TITLE
Unexpected token: name (raf) [./node_modules/resize-detector/esm/index.js:1,0

### ISSUE THREAD

**Issue by havefive** [Justineo/resize-detector#5]
vue-cli项目打包出现错误

ERROR in static/js/vendor.7b3b225cb350cfc2c808.js from UglifyJs
Unexpected token: name (raf) [./node_modules/resize-detector/esm/index.js:1,0

**Comment by Justineo** [comment]
CLI 版本？

**Comment by Justineo** [comment]
https://github.com/Justineo/resize-detector#heads-up

如果用 Vue CLI 3 的话可以在 `vue.config.js` 里加入 [`transpileDependencies`](https://cli.vuejs.org/zh/config/#transpiledependencies)。

**Comment by AlexanderZon** [comment]
I have the same problem with webpack
