### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by phoenixwong** [Justineo/resize-detector#8]
Recently our auto bug report system captured a `window.onerror` message `ResizeObserver loop limit exceeded` originate from this plugin.

Lattest report platform: Chrome v71.0.3578 + Chrome OS 11151.113

Seems to be a Chrome-specific issue for now. I searched around and found some related issues with fixes, FYI:

- https://github.com/souporserious/react-measure/issues/104
- https://github.com/hshoff/vx/pull/335
- https://github.com/d6u/react-container-query/issues/70

Hope it helps.

**Comment by Justineo** [comment]
Actually this message can be ignored safely ([source](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded)).
