### ISSUE TITLE
esm 在 ie 11 下报错

### ISSUE THREAD

**Issue by huangbinjie** [Justineo/resize-detector#9]
突然发现 ie 11 不支持默认值的写法。所以一旦 webpack 项目使用默认配置，就会打包 esm 下的 js 文件。这行代码会导致报错：https://github.com/Justineo/resize-detector/blob/dabe7fd83fe0c2865b5c16f48f4e27caceef326a/src/util.js#L45

我只是提个建议...感觉可以不处理

**Comment by Justineo** [comment]
需要进行转译。或者直接：

```js
import { addListener } from 'resize-detector/dist'
```

**Comment by huangbinjie** [comment]
这个好，谢谢了～
